namespace WDE.Common.Services;

public enum SpellAuraType : uint
{
    None                                         = 0,
    BindSight                                   = 1,
    ModPossess                                  = 2,
    PeriodicDamage                              = 3,
    Dummy                                        = 4,
    ModConfuse                                  = 5,
    ModCharm                                    = 6,
    ModFear                                     = 7,
    PeriodicHeal                                = 8,
    ModAttackspeed                              = 9,
    ModThreat                                   = 10,
    ModTaunt                                    = 11,
    ModStun                                     = 12,
    ModDamageDone                              = 13,
    ModDamageTaken                             = 14,
    DamageShield                                = 15,
    ModStealth                                  = 16,
    ModStealthDetect                           = 17,
    ModInvisibility                             = 18,
    ModInvisibilityDetect                      = 19,
    ObsModHealth                               = 20,   // 20, 21 unofficial
    ObsModPower                                = 21,
    ModResistance                               = 22,
    PeriodicTriggerSpell                       = 23,
    PeriodicEnergize                            = 24,
    ModPacify                                   = 25,
    ModRoot                                     = 26,
    ModSilence                                  = 27,
    ReflectSpells                               = 28,
    ModStat                                     = 29,
    ModSkill                                    = 30,
    ModIncreaseSpeed                           = 31,
    ModIncreaseMountedSpeed                   = 32,
    ModDecreaseSpeed                           = 33,
    ModIncreaseHealth                          = 34,
    ModIncreaseEnergy                          = 35,
    ModShapeshift                               = 36,
    EffectImmunity                              = 37,
    StateImmunity                               = 38,
    SchoolImmunity                              = 39,
    DamageImmunity                              = 40,
    DispelImmunity                              = 41,
    ProcTriggerSpell                           = 42,
    ProcTriggerDamage                          = 43,
    TrackCreatures                              = 44,
    TrackResources                              = 45,
    Aura46                                           = 46,   // Ignore all Gear test spells
    ModParryPercent                            = 47,
    PeriodicTriggerSpellFromClient           = 48,   // One periodic spell
    ModDodgePercent                            = 49,
    ModCriticalHealingAmount                  = 50,
    ModBlockPercent                            = 51,
    ModWeaponCritPercent                      = 52,
    PeriodicLeech                               = 53,
    ModHitChance                               = 54,
    ModSpellHitChance                         = 55,
    Transform                                    = 56,
    ModSpellCritChance                        = 57,
    ModIncreaseSwimSpeed                      = 58,
    ModDamageDoneCreature                     = 59,
    ModPacifySilence                           = 60,
    ModScale                                    = 61,
    PeriodicHealthFunnel                       = 62,
    ModAdditionalPowerCost                    = 63,
    PeriodicManaLeech                          = 64,
    ModCastingSpeedNotStack                  = 65,
    FeignDeath                                  = 66,
    ModDisarm                                   = 67,
    ModStalked                                  = 68,
    SchoolAbsorb                                = 69,
    PeriodicWeaponPercentDamage               = 70,
    StoreTeleportReturnPoint                  = 71,
    ModPowerCostSchoolPct                    = 72,
    ModPowerCostSchool                        = 73,
    ReflectSpellsSchool                        = 74,
    ModLanguage                                 = 75,
    FarSight                                    = 76,
    MechanicImmunity                            = 77,
    Mounted                                      = 78,
    ModDamagePercentDone                      = 79,
    ModPercentStat                             = 80,
    SplitDamagePct                             = 81,
    WaterBreathing                              = 82,
    ModBaseResistance                          = 83,
    ModRegen                                    = 84,
    ModPowerRegen                              = 85,
    ChannelDeathItem                           = 86,
    ModDamagePercentTaken                     = 87,
    ModHealthRegenPercent                     = 88,
    PeriodicDamagePercent                      = 89,
    Aura90                                           = 90,   // old MOD_RESIST_CHANCE
    ModDetectRange                             = 91,
    PreventsFleeing                             = 92,
    ModUnattackable                             = 93,
    InterruptRegen                              = 94,
    Ghost                                        = 95,
    SpellMagnet                                 = 96,
    ManaShield                                  = 97,
    ModSkillTalent                             = 98,
    ModAttackPower                             = 99,
    AurasVisible                                = 100,
    ModResistancePct                           = 101,
    ModMeleeAttackPowerVersus                = 102,
    ModTotalThreat                             = 103,
    WaterWalk                                   = 104,
    FeatherFall                                 = 105,
    Hover                                        = 106,
    AddFlatModifier                            = 107,
    AddPctModifier                             = 108,
    AddTargetTrigger                           = 109,
    ModPowerRegenPercent                      = 110,
    InterceptMeleeRangedAttacks               = 111,
    OverrideClassScripts                       = 112,
    ModRangedDamageTaken                      = 113,
    ModRangedDamageTakenPct                  = 114,
    ModHealing                                  = 115,
    ModRegenDuringCombat                      = 116,
    ModMechanicResistance                      = 117,
    ModHealingPct                              = 118,
    PvpTalents                                  = 119,
    Untrackable                                  = 120,
    Empathy                                      = 121,
    ModOffhandDamagePct                       = 122,
    ModTargetResistance                        = 123,
    ModRangedAttackPower                      = 124,
    ModMeleeDamageTaken                       = 125,
    ModMeleeDamageTakenPct                   = 126,
    RangedAttackPowerAttackerBonus           = 127,
    ModFixate                                   = 128,
    ModSpeedAlways                             = 129,
    ModMountedSpeedAlways                     = 130,
    ModRangedAttackPowerVersus               = 131,
    ModIncreaseEnergyPercent                  = 132,
    ModIncreaseHealthPercent                  = 133,
    ModManaRegenInterrupt                     = 134,
    ModHealingDone                             = 135,
    ModHealingDonePercent                     = 136,
    ModTotalStatPercentage                    = 137,
    ModMeleeHaste                              = 138,
    ForceReaction                               = 139,
    ModRangedHaste                             = 140,
    Aura141                                          = 141,  // old MOD_RANGED_AMMO_HASTE, unused now
    ModBaseResistancePct                      = 142,
    ModRecoveryRateBySpellLabel             = 143,  // NYI
    SafeFall                                    = 144,
    ModIncreaseHealthPercent2                 = 145,
    AllowTamePetType                          = 146,
    MechanicImmunityMask                       = 147,
    ModChargeRecoveryRate                     = 148,  // NYI
    ReducePushback                              = 149,  //    Reduce Pushback
    ModShieldBlockvaluePct                    = 150,
    TrackStealthed                              = 151,  //    Track Stealthed
    ModDetectedRange                           = 152,  //    Mod Detected Range
    ModAutoattackRange                         = 153,
    ModStealthLevel                            = 154,  //    Stealth Level Modifier
    ModWaterBreathing                          = 155,  //    Mod Water Breathing
    ModReputationGain                          = 156,  //    Mod Reputation Gain
    PetDamageMulti                             = 157,  //    Mod Pet Damage
    AllowTalentSwapping                        = 158,
    NoPvpCredit                                = 159,
    Aura160                                          = 160,  // old MOD_AOE_AVOIDANCE. Unused 4.3.4
    ModHealthRegenInCombat                   = 161,
    PowerBurn                                   = 162,
    ModCritDamageBonus                        = 163,
    ForceBreathBar                             = 164,
    MeleeAttackPowerAttackerBonus            = 165,
    ModAttackPowerPct                         = 166,
    ModRangedAttackPowerPct                  = 167,
    ModDamageDoneVersus                       = 168,
    SetFfaPvp                                  = 169,
    DetectAmore                                 = 170,
    ModSpeedNotStack                          = 171,
    ModMountedSpeedNotStack                  = 172,
    ModRecoveryRate2                          = 173,  // NYI
    ModSpellDamageOfStatPercent             = 174,  // by defeult intelect, dependent from MOD_SPELL_HEALING_OF_STAT_PERCENT
    ModSpellHealingOfStatPercent            = 175,
    SpiritOfRedemption                         = 176,
    AoeCharm                                    = 177,
    ModMaxPowerPct                            = 178,
    ModPowerDisplay                            = 179,
    ModFlatSpellDamageVersus                 = 180,
    ModSpellCurrencyReagentsCountPct        = 181,  // NYI
    SuppressItemPassiveEffectBySpellLabel  = 182,
    ModCritChanceVersusTargetHealth         = 183,
    ModAttackerMeleeHitChance                = 184,
    ModAttackerRangedHitChance               = 185,
    ModAttackerSpellHitChance                = 186,
    ModAttackerMeleeCritChance               = 187,
    ModAttackerRangedCritChance              = 188,
    ModRating                                   = 189,
    ModFactionReputationGain                  = 190,
    UseNormalMovementSpeed                    = 191,
    ModMeleeRangedHaste                       = 192,
    MeleeSlow                                   = 193,
    ModTargetAbsorbSchool                     = 194,
    LearnSpell                                  = 195,
    ModCooldown                                 = 196,  // only 24818 Noxious Breath
    ModAttackerSpellAndWeaponCritChance    = 197,
    ModCombatRatingFromCombatRating         = 198,
    Aura199                                          = 199,  // old MOD_INCREASES_SPELL_PCT_TO_HIT. unused 4.3.4
    ModXpPct                                   = 200,
    Fly                                          = 201,
    IgnoreCombatResult                         = 202,
    PreventInterrupt                            = 203,  // NYI
    PreventCorpseRelease                       = 204,  // NYI
    ModChargeCooldown                          = 205,  // NYI
    ModIncreaseVehicleFlightSpeed            = 206,
    ModIncreaseMountedFlightSpeed            = 207,
    ModIncreaseFlightSpeed                    = 208,
    ModMountedFlightSpeedAlways              = 209,
    ModVehicleSpeedAlways                     = 210,
    ModFlightSpeedNotStack                   = 211,
    ModHonorGainPct                           = 212,
    ModRageFromDamageDealt                   = 213,
    Aura214                                          = 214,
    ArenaPreparation                            = 215,
    HasteSpells                                 = 216,
    ModMeleeHaste2                            = 217,
    AddPctModifierBySpellLabel              = 218,
    AddFlatModifierBySpellLabel             = 219,
    ModAbilitySchoolMask                      = 220,  // NYI
    ModDetaunt                                  = 221,
    RemoveTransmogCost                         = 222,
    RemoveBarberShopCost                      = 223,
    LearnTalent                                 = 224,  // NYI
    ModVisibilityRange                         = 225,
    PeriodicDummy                               = 226,
    PeriodicTriggerSpellWithValue            = 227,
    DetectStealth                               = 228,
    ModAoeDamageAvoidance                     = 229,
    ModMaxHealth                               = 230,
    ProcTriggerSpellWithValue                = 231,
    MechanicDurationMod                        = 232,
    ChangeModelForAllHumanoids               = 233,  // client-side only
    MechanicDurationModNotStack              = 234,
    ModHoverNoHeightOffset                   = 235,
    ControlVehicle                              = 236,
    Aura237                                          = 237,
    Aura238                                          = 238,
    ModScale2                                  = 239,
    ModExpertise                                = 240,
    ForceMoveForward                           = 241,
    ModSpellDamageFromHealing                = 242,
    ModFaction                                  = 243,
    ComprehendLanguage                          = 244,
    ModAuraDurationByDispel                  = 245,
    ModAuraDurationByDispelNotStack        = 246,
    CloneCaster                                 = 247,
    ModCombatResultChance                     = 248,
    ModDamagePercentDoneByTargetAuraMechanic = 249, // NYI
    ModIncreaseHealth2                        = 250,
    ModEnemyDodge                              = 251,
    ModSpeedSlowAll                           = 252,
    ModBlockCritChance                        = 253,
    ModDisarmOffhand                           = 254,
    ModMechanicDamageTakenPercent            = 255,
    NoReagentUse                               = 256,
    ModTargetResistBySpellClass             = 257,
    OverrideSummonedObject                     = 258,
    ModHotPct                                  = 259,
    ScreenEffect                                = 260,
    Phase                                        = 261,
    AbilityIgnoreAurastate                     = 262,
    DisableCastingExceptAbilities             = 263,
    DisableAttackingExceptAbilities           = 264,
    Aura265                                          = 265,
    SetVignette                                 = 266,  // NYI
    ModImmuneAuraApplySchool                 = 267,
    ModArmorPctFromStat                      = 268,
    ModIgnoreTargetResist                     = 269,
    ModSchoolMaskDamageFromCaster           = 270,
    ModSpellDamageFromCaster                 = 271,
    ModBlockValuePct                          = 272,  // NYI
    XRay                                        = 273,
    ModBlockValueFlat                         = 274,  // NYI
    ModIgnoreShapeshift                        = 275,
    ModDamageDoneForMechanic                 = 276,
    Aura277                                          = 277,  // old MOD_MAX_AFFECTED_TARGETS. unused 4.3.4
    ModDisarmRanged                            = 278,
    InitializeImages                            = 279,
    Aura280                                          = 280,  // old MOD_ARMOR_PENETRATION_PCT unused 4.3.4
    ProvideSpellFocus                          = 281,
    ModBaseHealthPct                          = 282,
    ModHealingReceived                         = 283,  // Possibly only for some spell family class spells
    Linked                                       = 284,
    Linked2                                     = 285,
    ModRecoveryRate                            = 286,
    DeflectSpells                               = 287,
    IgnoreHitDirection                         = 288,
    PreventDurabilityLoss                      = 289,
    ModCritPct                                 = 290,
    ModXpQuestPct                             = 291,
    OpenStable                                  = 292,
    OverrideSpells                              = 293,
    PreventRegeneratePower                     = 294,
    ModPeriodicDamageTaken                    = 295,
    SetVehicleId                               = 296,
    ModRootDisableGravity                     = 297,  // NYI
    ModStunDisableGravity                     = 298,  // NYI
    Aura299                                          = 299,
    ShareDamagePct                             = 300,
    SchoolHealAbsorb                           = 301,
    Aura302                                          = 302,
    ModDamageDoneVersusAurastate             = 303,
    ModFakeInebriate                           = 304,
    ModMinimumSpeed                            = 305,
    ModCritChanceForCaster                   = 306,
    CastWhileWalkingBySpellLabel            = 307,
    ModCritChanceForCasterWithAbilities    = 308,
    ModResilience                               = 309,  // NYI
    ModCreatureAoeDamageAvoidance            = 310,
    IgnoreCombat                                = 311,  // NYI
    AnimReplacementSet                         = 312,
    MountAnimReplacementSet                   = 313,
    PreventResurrection                         = 314,
    UnderwaterWalking                           = 315,
    SchoolAbsorbOverkill                       = 316,  // NYI - absorbs overkill damage
    ModSpellPowerPct                          = 317,
    Mastery                                      = 318,
    ModMeleeHaste3                            = 319,
    Aura320                                          = 320,
    ModNoActions                               = 321,
    InterfereTargetting                         = 322,
    Aura323                                          = 323,  // Not used in 4.3.4
    OverrideUnlockedAzeriteEssenceRank       = 324,  // testing aura
    LearnPvpTalent                             = 325,  // NYI
    PhaseGroup                                  = 326,  // Puts the player in all the phases that are in the group with id = miscB
    PhaseAlwaysVisible                         = 327,  // Sets PhaseShiftFlags::AlwaysVisible
    TriggerSpellOnPowerPct                   = 328,  // Triggers spell when power goes above (MiscB = 0) or falls below (MiscB = 1) specified percent value (once, not every time condition has meet)
    ModPowerGainPct                           = 329,
    CastWhileWalking                           = 330,
    ForceWeather                                = 331,
    OverrideActionbarSpells                    = 332,
    OverrideActionbarSpellsTriggered          = 333,  // Spells cast with this override have no cast time or power cost
    ModAutoattackCritChance                   = 334,
    Aura335                                          = 335,
    MountRestrictions                           = 336,
    ModVendorItemsPrices                      = 337,
    ModDurabilityLoss                          = 338,
    ModCritChanceForCasterPet               = 339,
    ModResurrectedHealthByGuildMember       = 340,  // Increases health gained when resurrected by a guild member by X
    ModSpellCategoryCooldown                  = 341,  // Modifies cooldown of all spells using affected category
    ModMeleeRangedHaste2                     = 342,
    ModMeleeDamageFromCaster                 = 343,
    ModAutoattackDamage                        = 344,
    BypassArmorForCaster                      = 345,
    EnableAltPower                             = 346,
    ModSpellCooldownByHaste                  = 347,
    ModMoneyGain                               = 348,  // Modifies gold gains from source: [Misc = 0, Quests][Misc = 1, Loot]
    ModCurrencyGain                            = 349,
    Aura350                                          = 350,
    ModCurrencyCategoryGainPct               = 351,  // NYI
    Aura352                                          = 352,
    ModCamouflage                               = 353,  // NYI
    ModHealingDonePctVersusTargetHealth    = 354,  // Restoration Shaman mastery - mod healing based on target's health (less = more healing)
    ModCastingSpeed                            = 355,  // NYI
    ProvideTotemCategory                       = 356,
    EnableBoss1UnitFrame                      = 357,
    WorgenAlteredForm                          = 358,
    ModHealingDoneVersusAurastate            = 359,
    ProcTriggerSpellCopy                      = 360,  // Procs the same spell that caused this proc (Dragonwrath, Tarecgosa's Rest)
    OverrideAutoattackWithMeleeSpell         = 361,
    Aura362                                          = 362,  // Not used in 4.3.4
    ModNextSpell                               = 363,  // Used by 101601 Throw Totem - causes the client to initialize spell cast with specified spell
    Aura364                                          = 364,  // Not used in 4.3.4
    MaxFarClipPlane                           = 365,  // Overrides client's View Distance setting to max("Fair", current_setting) and turns off terrain display
    OverrideSpellPowerByApPct               = 366,  // NYI - Sets spellpower equal to % of attack power, discarding all other bonuses (from gear and buffs)
    OverrideAutoattackWithRangedSpell        = 367,  // NYI
    Aura368                                          = 368,  // Not used in 4.3.4
    EnablePowerBarTimer                       = 369,
    SpellOverrideNameGroup                    = 370,  // picks a random SpellOverrideName id from a group (group id in miscValue)
    Aura371                                          = 371,
    OverrideMountFromSet                      = 372,  // NYI
    ModSpeedNoControl                         = 373,  // NYI
    ModifyFallDamagePct                       = 374,
    HideModelAndEquipementSlots              = 375,
    ModCurrencyGainFromSource                = 376,  // NYI
    CastWhileWalkingAll                       = 377,  // Enables casting all spells while moving
    ModPossessPet                              = 378,
    ModManaRegenPct                           = 379,
    Aura380                                          = 380,
    ModDamageTakenFromCasterPet             = 381,  // NYI
    ModPetStatPct                             = 382,  // NYI
    IgnoreSpellCooldown                        = 383,  // NYI
    Aura384                                          = 384,
    Aura385                                          = 385,
    Aura386                                          = 386,
    Aura387                                          = 387,
    ModTaxiFlightSpeed                        = 388,  // NYI
    Aura389                                          = 389,
    Aura390                                          = 390,
    Aura391                                          = 391,
    Aura392                                          = 392,
    BlockSpellsInFront                        = 393,  // NYI
    ShowConfirmationPrompt                     = 394,
    AreaTrigger                                 = 395,  // NYI
    TriggerSpellOnPowerAmount                = 396,  // Triggers spell when power goes above (MiscA = 0) or falls below (MiscA = 1) specified percent value (once, not every time condition has meet)
    BattlegroundPlayerPositionFactional       = 397,
    BattlegroundPlayerPosition                 = 398,
    ModTimeRate                                = 399,
    ModSkill2                                  = 400,
    Aura401                                          = 401,
    ModOverridePowerDisplay                   = 402,
    OverrideSpellVisual                        = 403,
    OverrideAttackPowerBySpPct              = 404,
    ModRatingPct                               = 405,
    KeyboundOverride                            = 406,  // NYI
    ModFear2                                   = 407,  // NYI
    SetActionButtonSpellCount                = 408,
    CanTurnWhileFalling                       = 409,
    Aura410                                          = 410,
    ModMaxCharges                              = 411,
    Aura412                                          = 412,
    ModRangedAttackDeflectChance             = 413,  // NYI
    ModRangedAttackBlockChanceInFront      = 414,  // NYI
    Aura415                                          = 415,
    ModCooldownByHasteRegen                  = 416,
    ModGlobalCooldownByHasteRegen           = 417,
    ModMaxPower                                = 418,  // NYI
    ModBaseManaPct                            = 419,
    ModBattlePetXpPct                        = 420,
    ModAbsorbEffectsDonePct                  = 421,  // NYI
    ModAbsorbEffectsTakenPct                 = 422,  // NYI
    ModManaCostPct                            = 423,
    CasterIgnoreLos                            = 424,  // NYI
    Aura425                                          = 425,
    Aura426                                          = 426,
    ScalePlayerLevel                           = 427,  // NYI
    LinkedSummon                                = 428,
    ModSummonDamage                            = 429,  // NYI - increases damage done by all summons, not just controlled pets
    PlayScene                                   = 430,
    ModOverrideZonePvpType                   = 431,  // NYI
    Aura432                                          = 432,
    Aura433                                          = 433,
    Aura434                                          = 434,
    Aura435                                          = 435,
    ModEnvironmentalDamageTaken               = 436,
    ModMinimumSpeedRate                       = 437,
    PreloadPhase                                = 438,  // NYI
    Aura439                                          = 439,
    ModMultistrikeDamage                       = 440,  // NYI
    ModMultistrikeChance                       = 441,  // NYI
    ModReadiness                                = 442,  // NYI
    ModLeech                                    = 443,  // NYI
    Aura444                                          = 444,
    Aura445                                          = 445,
    Aura446                                          = 446,
    ModXpFromCreatureType                    = 447,
    Aura448                                          = 448,
    Aura449                                          = 449,
    Aura450                                          = 450,
    OverridePetSpecs                           = 451,
    Aura452                                          = 452,
    ChargeRecoveryMod                          = 453,
    ChargeRecoveryMultiplier                   = 454,
    ModRoot2                                   = 455,
    ChargeRecoveryAffectedByHaste            = 456,
    ChargeRecoveryAffectedByHasteRegen      = 457,
    IgnoreDualWieldHitPenalty                = 458,
    IgnoreMovementForces                       = 459,
    ResetCooldownsOnDuelStart                = 460,  // NYI
    Aura461                                          = 461,
    ModHealingAndAbsorbFromCaster           = 462,  // NYI
    ConvertCritRatingPctToParryRating      = 463,  // NYI
    ModAttackPowerOfBonusArmor              = 464,  // NYI
    ModBonusArmor                              = 465,
    ModBonusArmorPct                          = 466,  // Affects bonus armor gain from all sources except base stats
    ModStatBonusPct                           = 467,  // Affects stat gain from all sources except base stats
    TriggerSpellOnHealthPct                  = 468,  // Triggers spell when health goes above (MiscA = 0) or falls below (MiscA = 1) specified percent value (once, not every time condition has meet)
    ShowConfirmationPromptWithDifficulty     = 469,
    ModAuraTimeRateBySpellLabel            = 470,  // NYI
    ModVersatility                              = 471,
    Aura472                                          = 472,
    PreventDurabilityLossFromCombat          = 473,  // Prevents durability loss from dealing/taking damage
    ReplaceItemBonusTree                      = 474,  // NYI
    AllowUsingGameobjectsWhileMounted        = 475,
    ModCurrencyGainLooted                     = 476,
    Aura477                                          = 477,
    Aura478                                          = 478,
    Aura479                                          = 479,
    ModArtifactItemLevel                      = 480,
    ConvertConsumedRune                        = 481,
    Aura482                                          = 482,
    SuppressTransforms                          = 483,  // NYI
    AllowInterruptSpell                        = 484,  // NYI
    ModMovementForceMagnitude                 = 485,
    Aura486                                          = 486,
    CosmeticMounted                             = 487,
    Aura488                                          = 488,
    ModAlternativeDefaultLanguage             = 489,
    Aura490                                          = 490,
    Aura491                                          = 491,
    Aura492                                          = 492,
    Aura493                                          = 493, // 1 spell, 267116 - Animal Companion (modifies Call Pet)
    SetPowerPointCharge                       = 494, // NYI
    TriggerSpellOnExpire                      = 495,
    AllowChangingEquipmentInTorghast         = 496, // NYI
    ModAnimaGain                               = 497, // NYI
    CurrencyLossPctOnDeath                   = 498, // NYI
    ModRestedXpConsumption                    = 499,
    IgnoreSpellChargeCooldown                 = 500, // NYI
    ModCriticalDamageTakenFromCaster        = 501,
    ModVersatilityDamageDoneBenefit          = 502, // NYI
    ModVersatilityHealingDoneBenefit         = 503, // NYI
    ModHealingTakenFromCaster                = 504,
    ModPlayerChoiceRerolls                    = 505, // NYI
    DisableInertia                              = 506,
    ModDamageTakenFromCasterByLabel        = 507,
    Aura508                                          = 508,
    Aura509                                          = 509,
    ModifiedRaidInstance                       = 510, // NYI; Related to "Fated" raid affixes
    ApplyProfessionEffect                      = 511, // NYI; MiscValue[0] = ProfessionEffectID
    Aura512                                          = 512,
    Aura513                                          = 513,
    Aura514                                          = 514,
    Aura515                                          = 515,
    Aura516                                          = 516,
    Aura517                                          = 517,
    Aura518                                          = 518,
    ModCooldownRecoveryRateAll               = 519, // NYI; applies to all spells, not filtered by familyflags or label
    Aura520                                          = 520,
    Aura521                                          = 521,
    Aura522                                          = 522,
    Aura523                                          = 523,
    Aura524                                          = 524,
    DisplayProfessionEquipment                 = 525, // NYI; MiscValue[0] = Profession (enum, not id)
    Aura526                                          = 526,
    Aura527                                          = 527,
    AllowBlockingSpells                        = 528, // NYI
    ModSpellBlockChance                       = 529, // NYI
    Aura530                                          = 530,
    Aura531                                          = 531,
    Aura532                                          = 532,
    DisableNavigation                           = 533, // disables map pins
    Aura534                                          = 534,
    Aura535                                          = 535, // related to profession equipment; NYI; MiscValue[0] = Profession (enum, not id)
    TotalAuras
}