<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <AvaloniaVersion>12.1.0</AvaloniaVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.1" />
        <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.3" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" Version="12.0.0.1" />
        <PackageReference Include="Optris.Icons.Avalonia" Version="12.0.7" />
        <PackageReference Include="Optris.Icons.Avalonia.MaterialDesign" Version="12.0.7" />
        <ProjectReference Include="$(MSBuildThisFileDirectory)\Prism.Avalonia\src\Prism.Avalonia\Prism.Avalonia.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="**\*.xaml.cs">
            <DependentUpon>%(Filename)</DependentUpon>
        </Compile>
        <AvaloniaResource Include="**\*.xaml">
            <SubType>Designer</SubType>
        </AvaloniaResource>
    </ItemGroup>
</Project>
