using System;
using System.Linq;
using WDE.Common.Database;
using WDE.Common.Parameters;
using WDE.Parameters.Models;

namespace WDE.DbScriptsEditor.Models
{
    // A single editor row. In the EDITOR, actions, waits and comments are equal, independent
    // entities: they can be reordered, selected, copied and deleted like any other row. Only on
    // save are they "squashed" into physical dbscript lines (waits accumulate into the delay
    // column, comments attach to the comment column of the next action / a trailing fake row);
    // on load the same derivation runs in reverse.
    public abstract class DbScriptRow : BulkEditableBase
    {
        // Whether this row belongs to the "if" block opened by the nearest preceding DbScriptIfRow.
        // Editor state like row order (undoable via InIfChanged); a block = an if row + the
        // unbroken run of InIf rows directly after it. Compiled into each action's condition_id
        // column by SyncDerived. Meaningless on DbScriptIfRow itself (blocks don't nest).
        private bool inIf;
        public bool InIf
        {
            get => inIf;
            set
            {
                if (inIf == value)
                    return;
                inIf = value;
                RaisePropertyChanged(nameof(InIf));
                InIfChanged?.Invoke(this, !value, value);
            }
        }

        public event Action<DbScriptRow, bool, bool>? InIfChanged;
    }

    // "if <condition>" — a pure editor entity opening a condition block. The unbroken run of InIf
    // rows after it are its members; member actions get its ConditionId compiled into their
    // condition_id column on save. An if row with no members exports nothing: it is a UI-only
    // placeholder that stays until the user puts commands under it or deletes it.
    public class DbScriptIfRow : DbScriptRow
    {
        public ParameterValueHolder<long> ConditionId { get; }

        public DbScriptIfRow(IParameterFactory factory, long conditionId)
        {
            ConditionId = new ParameterValueHolder<long>("Condition", factory.Factory(null), conditionId);
        }
    }

    // "⏱ wait N ms" — a pure editor entity representing a time gap between rows.
    public class DbScriptWaitRow : DbScriptRow
    {
        public ParameterValueHolder<long> Duration { get; }

        // Derived: absolute time (ms) at which this wait starts, recomputed by the script
        // whenever rows change. Display-only.
        private long startsAt;
        public long StartsAt
        {
            get => startsAt;
            set
            {
                if (SetProperty(ref startsAt, value))
                    RaisePropertyChanged(nameof(EndsAt));
            }
        }

        public long EndsAt => startsAt + Duration.Value;

        public DbScriptWaitRow(IParameterFactory factory, long durationMs)
        {
            Duration = new ParameterValueHolder<long>("Wait (ms)", factory.Factory(null), durationMs);
            Duration.PropertyChanged += (_, _) => RaisePropertyChanged(nameof(EndsAt));
        }
    }

    // "// text" — a standalone comment line. Attached to the next action's comment column on save.
    public class DbScriptCommentRow : DbScriptRow
    {
        public ParameterValueHolder<string> Text { get; }

        public DbScriptCommentRow(IParameterFactory factory, string text)
        {
            Text = new ParameterValueHolder<string>("Comment", factory.FactoryString(null), text);
        }
    }

    // The SmartScript-style stored comment convention: "<autogenerated readable> // <custom>".
    public static class DbScriptCommentConvention
    {
        public const string Separator = " // ";

        // "<autogen> // <custom>" → custom. A comment with no separator is a legacy hand comment
        // (no autogen half) — kept whole so real cmangos scripts don't lose comments. (Our
        // exporter ALWAYS writes the separator, so our own re-imports never hit that branch.)
        public static string ExtractCustom(string? stored)
        {
            if (string.IsNullOrEmpty(stored))
                return "";
            var idx = stored.IndexOf(Separator, StringComparison.Ordinal);
            return (idx >= 0 ? stored.Substring(idx + Separator.Length) : stored).Trim();
        }

        // The full column value to store; the separator is always present so re-imports parse
        // unambiguously (custom may be empty).
        public static string Compose(string autogen, string custom) => $"{autogen}{Separator}{custom}";

        // Trailing comments (no action after them) are persisted as a "fake" command-0 line with
        // no data whatsoever, only the comment column. Detect those on load so they come back as
        // pure comment rows.
        public static bool IsFakeCommentLine(IDbScriptLine line)
        {
            if (line.Command != 0)
                return false;
            if (line.DataLong != 0 || line.DataLong2 != 0 || line.DataLong3 != 0 ||
                line.DataInt != 0 || line.DataInt2 != 0 || line.DataInt3 != 0 || line.DataInt4 != 0 ||
                line.BuddyEntry != 0 || line.SearchRadius != 0 || line.DataFlags != 0 ||
                line.ConditionId != 0)
                return false;
            if (line.DataFloat != 0 || line.X != 0 || line.Y != 0 || line.Z != 0 || line.O != 0 || line.Speed != 0)
                return false;
            return ExtractCustom(line.Comments).Length > 0;
        }

        // Comments joined into one column value / split back into rows.
        public static string Join(System.Collections.Generic.IEnumerable<string> comments) =>
            string.Join("\n", comments);

        public static string[] Split(string custom) =>
            custom.Split('\n', StringSplitOptions.RemoveEmptyEntries).Select(c => c.Trim()).ToArray();
    }
}
