using System.Collections.Generic;
using WDE.Common.Database;
using WDE.Common.Utils;
using WDE.DbScriptsEditor.Models;
using WDE.Module.Attributes;
using WDE.SqlQueryGenerator;

namespace WDE.DbScriptsEditor.Exporter
{
    [UniqueProvider]
    public interface IDbScriptExporter
    {
        IQuery GenerateSql(EditableDbScript script);
    }

    // DELETE FROM <table> WHERE id = X;  +  a single multi-row INSERT in schema column order.
    // This is where the editor's flat row list (action | wait | comment) is SQUASHED into physical
    // dbscript lines: waits accumulate into the delay column, comment rows attach to the next
    // action's comment column, trailing comments become a fake command-0 comment-only line.
    // priority is renumbered 0..n from the current row order (gaps are not preserved).
    [AutoRegister]
    [SingleInstance]
    public class DbScriptExporter : IDbScriptExporter
    {
        public IQuery GenerateSql(EditableDbScript script)
        {
            var table = DatabaseTable.WorldTable(script.TypeInfo.TableName);
            var query = Queries.BeginTransaction(DataDatabaseType.World);
            query.Comment($"{script.TypeInfo.ReadableName} {script.ScriptId}");

            query.Table(table)
                .Where(r => r.Column<long>("id") == (long)script.ScriptId)
                .Delete();

            var rows = new List<object>();
            long delay = 0;
            uint priority = 0;
            var pendingComments = new List<string>();
            foreach (var row in script.Rows)
            {
                switch (row)
                {
                    case DbScriptWaitRow wait:
                        delay += wait.Duration.Value;
                        break;
                    case DbScriptCommentRow comment:
                        if (!string.IsNullOrWhiteSpace(comment.Text.Value))
                            pendingComments.Add(comment.Text.Value.Trim());
                        break;
                    case EditableDbScriptStep step:
                        rows.Add(SerializeStep(script.ScriptId, (uint)delay, priority++, step,
                            DbScriptCommentConvention.Join(pendingComments)));
                        pendingComments.Clear();
                        break;
                }
            }

            // Trailing comments with no action after them: a fake command-0 line carrying only
            // the comment column, so they survive a save/load roundtrip.
            if (pendingComments.Count > 0)
                rows.Add(SerializeFakeCommentLine(script.ScriptId, (uint)delay, priority,
                    DbScriptCommentConvention.Join(pendingComments)));

            if (rows.Count > 0)
                query.Table(table).BulkInsert(rows);

            return query.Close();
        }

        // NOTE: BulkInsert requires every row object to be the SAME anonymous type, so this must
        // mirror SerializeStep's property names, order and types exactly.
        private static object SerializeFakeCommentLine(uint scriptId, uint delay, uint priority, string comment)
        {
            return new
            {
                id = scriptId,
                delay = delay,
                priority = priority,
                command = 0u,
                datalong = 0u, datalong2 = 0u, datalong3 = 0u,
                buddy_entry = 0u, search_radius = 0u, data_flags = 0u,
                dataint = 0, dataint2 = 0, dataint3 = 0, dataint4 = 0,
                datafloat = 0f, x = 0f, y = 0f, z = 0f, o = 0f, speed = 0f,
                condition_id = 0u,
                comments = DbScriptCommentConvention.Compose("", comment),
            };
        }

        private static object SerializeStep(uint scriptId, uint delay, uint priority, EditableDbScriptStep step, string customComment)
        {
            var line = step.ToLine();
            // "<autogenerated readable> // <custom comment>" (custom may be empty).
            var comment = DbScriptCommentConvention.Compose(step.Readable.RemoveTags(), customComment);

            return new
            {
                id = scriptId,
                delay = delay,
                priority = priority,
                command = line.Command,
                datalong = line.DataLong,
                datalong2 = line.DataLong2,
                datalong3 = line.DataLong3,
                buddy_entry = line.BuddyEntry,
                search_radius = line.SearchRadius,
                data_flags = line.DataFlags,
                dataint = line.DataInt,
                dataint2 = line.DataInt2,
                dataint3 = line.DataInt3,
                dataint4 = line.DataInt4,
                datafloat = line.DataFloat,
                x = line.X,
                y = line.Y,
                z = line.Z,
                o = line.O,
                speed = line.Speed,
                condition_id = line.ConditionId,
                comments = comment,
            };
        }
    }
}
